FROM node:23

WORKDIR /app

COPY package* .
RUN npm install
RUN npm audit fix

COPY . .

RUN npm install -g wait-port

CMD ["sh", "-c", "wait-port mysql:3306 && npx prisma migrate dev && npm run seed && npm run dev"]
